trigger:
- master

pool: Tolga-ios

steps:
- script: |
    dotnet sonarscanner begin /k:"MenuMaster-BackEnd--T3-" /d:sonar.host.url="http://localhost:9000" /d:sonar.token="$(token)"
  displayName: 'SonarQube Begin'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'MenuMasterIosApp'
    configuration: 'Development'
    xcWorkspacePath: 'MenuMasterIosApp.xcodeproj/project.xcworkspace'
    sdk: 'Iphonesimulator'
    buildArguments: '-derivedDataPath Build/'
    args: '-destination "platform=iOS Simulator,name=iPhone Prod iOS17" -derivedDataPath Build/ -enableCodeCoverage YES'
